#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - make test