n_runs: 1
n_splits: 0
learning_rate: 0.00038810100479654000
train_batch_size: 419
val_batch_size: 64
train_steps: 1161
pooling_mode: max
raw_train_path: /Users/bas/PycharmProjects/jarvis2/data/20231106_105236_dip_train_2023_2_0_20x300_23432.csv
raw_test_path: /Users/bas/PycharmProjects/jarvis2/data/eqk_validation_enriched_0_20x300_800.csv
val_steps: 100
hidden_dim: 600
readout_dim: 142
n_ffn_blocks_emb: 1
n_ffn_blocks_readout: 2
cache_embeddings: True
exp_name: enriched_eqk_073_5fold_f1
dropout_rate: 0.03993953731992860
loss_fn: cosine
es_delta: 0.0
allow_half_label: True
es_patience: 10
siamese: True
#model_name: sentence-transformers/all-mpnet-base-v2
remove_synonym_skills: True
remove_strange_skills: False
rename_skills: False
neg_label_bias: 0.18535713430093400
num_heads: 4
pos_label_bias: 0.19948976499624800
train_weight_decay: 9.78212150724262E-06