n_runs: 1
n_splits: 0
val_batch_size: 64
raw_train_path: /Users/bas/PycharmProjects/jarvis2/data/dip_train_2023_3_extractedskills.csv
raw_test_path: /Users/bas/PycharmProjects/jarvis2/data/eqk_validation_extracted_skills_0_20x300_800.csv
val_steps: 100
cache_embeddings: True
exp_name: best_jobtitle_eqk_0742_5fold_f1
loss_fn: cosine
es_delta: 0.0
allow_half_label: True
es_patience: 10
remove_synonym_skills: True
remove_strange_skills: False
rename_skills: False
preprocess_jobtitle: True

dropout_rate: 0.0308923435716652
hidden_dim: 600
learning_rate: 5.75714431529286E-05
model_name: "sentence-transformers/all-mpnet-base-v2"
n_ffn_blocks_emb: 2
n_ffn_blocks_readout: 2
neg_label_bias: 0.295087646724669
negative_ratio: 0.976093953626082
num_heads: 3
pooling_mode: "mean"
pos_label_bias: 0.194618002052236
readout_dim: 158
siamese: FALSE
train_batch_size: 396
train_steps: 1655
use_jobtitle: TRUE
weight_decay: 6.7551467636942E-08