allow_half_label: true
n_runs: 1
alpha: 0
cache_embeddings: true
commit_hash: f7fefaf8f1562848f9e9b131dfb57fab27d61dd4
do_msm: true
dropout_rate: 0.15
es_delta: 0.01
es_patience: 5
exp_name: msm_base_model_best
finetune_lr: 1.0e-07
fp16: false
group_hashed: true
group_name: cv
hidden_dim: 600
learning_rate: 1.2374532963784292e-05
log_level: INFO
loss_fn: contrastive
lower_is_better: false
max_len: 64
max_skills: 20
model_name: sentence-transformers/all-mpnet-base-v2
msm_lr: 0.0001
msm_train_batch_size: 256
msm_train_steps: 7998
msm_val_batch_size: 512
msm_val_steps: 100
msm_weight_decay: 1.0e-08
n_ffn_blocks_emb: 1
n_ffn_blocks_readout: 1
n_splits: 0
n_thresholds: 100
n_workers: 0
neg_label_bias: 0.0
negative_ratio: 1
negative_sampling: true
num_heads: 12
p_add_skill: 0.0
p_change_skill: 0.0
p_remove_skill: 0.0
pooling_mode: cls
pos_label_bias: 0.0
preprocess_jobtitle: true
pretrained_path: ''
random_sampler: false
raw_test_path: /Users/bas/PycharmProjects/jarvis2/data/eqk_validation_enriched_0_20x300_800.csv
raw_train_path: /Users/bas/PycharmProjects/jarvis2/data/dip_train_2024_1_combinedskills.csv
readout_dim: 300
remove_strange_skills: false
remove_synonym_skills: false
rename_skills: false
run_idx: 16
score_metric: msm_accuracy
seed: 1997
siamese: true
skill_prefix: ''
train_batch_size: 4
train_steps: 1
use_jobtitle: false
val_batch_size: 4
val_steps: 1
warmup_ratio: 0.1
weight_decay: 0.0001
