allow_half_label: true
n_runs: 20
alpha: 0
cache_embeddings: true
commit_hash: f7fefaf8f1562848f9e9b131dfb57fab27d61dd4
do_msm: false
dropout_rate:
  low: 0
  high: 0.05
es_delta: 0.0
es_patience: 10
exp_name: msm_base_finetuning
fp16: false
group_hashed: true
group_name: cv
hidden_dim: 600
log_level: INFO
loss_fn: cosine
lower_is_better: false
max_len: 64
max_skills: 20
model_name: sentence-transformers/all-mpnet-base-v2
msm_lr: 0.0001
msm_train_batch_size: 256
msm_train_steps: 7998
msm_val_batch_size: 512
msm_val_steps: 100
msm_weight_decay: 1.0e-08
n_ffn_blocks_emb: 1
n_ffn_blocks_readout: 1
n_splits: 0
n_thresholds: 100
n_workers: 0
negative_ratio: 1
negative_sampling: true
num_heads: 12
p_add_skill: 0.0
p_change_skill: 0.0
p_remove_skill: 0.0
pooling_mode: cls
preprocess_jobtitle: true
pretrained_path: /Users/bas/PycharmProjects/jarvis2/output/msm_base_model_best/2024_01_15_15_33_27/run0_msm/encoder_weights.pth
random_sampler: false
raw_test_path: /Users/bas/PycharmProjects/jarvis2/data/eqk_validation_enriched_0_20x300_800.csv
raw_train_path: /Users/bas/PycharmProjects/jarvis2/data/20231106_105236_dip_train_2023_2_0_20x300_23432.csv
readout_dim: 300
remove_strange_skills: false
remove_synonym_skills: false
rename_skills: false
run_idx: 16
score_metric: val_all_f1
seed: 1997
siamese: true
skill_prefix: ''
train_batch_size:
  low: 256
  high: 512
  int: true
train_steps:
  low: 500
  high: 2000
  int: true
finetune_lr:
  low: 0.00000001
  high: 0.000001
  log: true
learning_rate:
  low: 0.00004
  high: 0.004
  log: true

use_jobtitle: false
val_batch_size: 64
val_steps: 100
warmup_ratio: 0.1
weight_decay: 0.0

neg_label_bias: 0.18535713430093400
pos_label_bias: 0.19948976499624800
train_weight_decay: 9.78212150724262E-06